### ISSUE TITLE
Shift+Click not work to do hard refresh

### ISSUE THREAD

**Issue by ReporterX** [hensm/reloader#12]
Shift+Click does not work to do hard refresh. 

I know there is a limitation, but wouldn't it be possible by placing a Javascript file?
If so, how? Thank you.

**Comment by hensm** [comment]
I don’t believe so. You can only do this if you can execute code in a privileged context. Technically possible (see userchrome.js), but out of scope for the extension.

**Comment by ReporterX** [comment]
Do you know what code we need to put in the userchrome.js?

I think it is a good solution (even though achieved by userchrome.js) since it will be fully functional and a complete replacement of the official reload button. I think some users are interested in that. 

As long as there is a instruction to tell users how to do, it is not a problem.

**Comment by hensm** [comment]
If you start messing with that, you may as well just move the regular reload button into the url bar. I suppose if you wanted to add hard reload to the extension button, you'd add a click handler and check the `MouseEvent.shiftKey` property, then call `reloadWithFlags`.

Something along the lines of (untested):

````js
const reloadButton = document.querySelector(
    `#reloader_matt_tf-page-action
   , #pageAction-urlbar-reloader_matt_tf`);

reloadButton.addEventListener("click", ev => {
    if (ev.shiftKey) {
        ev.preventDefault();

        gBrowser.reloadWithFlags(
            gBrowser.webNavigation.LOAD_FLAGS_BYPASS_CACHE);
    }
});
````
