### ISSUE TITLE
custom colors opacity please

### ISSUE THREAD

**Issue by drmusti** [hensm/reloader#4]
hi deasr coder.
custom colors opacity please
#reloader_matt_tf-page-action  {
 color: red !important; 
 
 }  
  
.reloader_matt_tf-page-action  {
 color: red !important; 
 
 }   
  
  i try  this css id  or class but dont work :( please help.
great addon. thanks.

**Comment by hensm** [comment]
Fixed in #2

More info in the README:
https://github.com/hensm/reloader#customizing
