### ISSUE TITLE
wrong class or id

### ISSUE THREAD

**Issue by drmusti** [hensm/reloader#5]
#reloader_matt_tf,#pageAction-urlbar-reloader_matt_tf,.reloader_matt_tf,.pageAction-urlbar-reloader_matt_tf {
    fill: red!important;
    fill-opacity: 0.3!important;
	context-fill:red!important;
	context-fill-opacity:0.3!important;
	
	
	
}

i made  svg.context-properties.content.enabled   true  
but dont work.
because no class or id your xpi files. i extracted your xpi with 7z.   no any class or id.
sincerely.

**Comment by hensm** [comment]
Use the example selector. First one is for Firefox 57, second is for versions after.

````css
#reloader_matt_tf-page-action,
#pageAction-urlbar-reloader_matt_tf {

}
````

The ID is generated and set by Firefox. I don't choose it.

**Comment by drmusti** [comment]
#reloader_matt_tf-page-action,
#pageAction-urlbar-reloader_matt_tf {
color:#4B4C4C !important;
}
 
 #reloader_matt_tf-page-action:hover,
#pageAction-urlbar-reloader_matt_tf:hover {
color:darkgreen !important;
}
great working at ff 57 very thanks :)
