### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by rayman89** [hensm/reloader#6]
Could you add the option to have a button instead of an icon in the url bar? I would like to replace the normal reload/stop button with yours.

BTW is it possible for web extensions to do different stuff when their button is pressed while a key is held? EX control + click on the button. I remember a legacy extension did this. If it possible that would be cool to be able to  do hard reload + clear cache with that combination.

BTW what is hard reload i thought it was to clear cache and reload but it seems to not be that.

**Comment by hensm** [comment]
I think it's possible. Seems reasonable, I'll probably add this.

The modifier key thing won't work though. There's no way to know what keys are being pressed. Other than a sort of hacky thing with content scripts, but it's too unreliable.

A hard reload bypasses the cache for anything queued with the initial page load. The clear cache and hard reload clears the global cache so it also works for sites where stuff is dynamically loaded.

**Comment by hensm** [comment]
Implemented: 7ff2703

Will push a new release later.

**Comment by hensm** [comment]
Uploaded to AMO.
