### ISSUE TITLE
about:debugging error message

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [hensm/reloader#7]
If you load about:debugging and view Reloader's entry, it says (Firefox 57)

> Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

Not a big deal, the extension still works :) But the perfectionist in me is screaming!  Shouldn't the manifest set `persistent": true` ?

Edit: typos

**Comment by hensm** [comment]
Yeah, that's just something I'm used to putting in from Chrome extensions. Event pages are supported everywhere else, and I'm guessing by the wording that Firefox might implement it in the future.

It doesn't break anything, it's just ignored. So, I'll probably just leave it in.

**Comment by Thorin-II** [comment]
> but the perfectionist in me is screaming!!!

I am not sure how I will be able to sleep nights anymore :)
