### ISSUE TITLE
White button for dark themes

### ISSUE THREAD

**Issue by rayman89** [hensm/reloader#8]
If it's not ttoo mcuh to ask could you make the reload button be white for dark firefox themes?

**Comment by hensm** [comment]
It's white on the built-in dark theme. I need to change it to use the new [theme API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/getCurrent), but I'll have to wait until FF58 or it's just going to get really messy.

**Comment by rayman89** [comment]
I see thank you.

**Comment by hensm** [comment]
Ah, turns out that API only works for extension-set themes. This probably isn't going to be possible unless the API is extended.

The only mechanism for specifying theme-specific icons is with the `theme_icons` manifest key. That only allows for one set of icons (this extension uses four sets).

**Comment by rayman89** [comment]
Thatt's odd I'm pretty sure I've other extensions have it but couldnt you add an option to allow the user to decide white or black ?

**Comment by hensm** [comment]
If you can remember which extensions, that would be helpful. Otherwise, I'll probably have to add an option, yep.

In the meantime, you can enable `svg.context-properties.content.enabled`, and that'll inherit the colors from the theme.

**Comment by rayman89** [comment]
Here I asked for the same thing for an other addon and the next time the icon was white. I'm not sure if he just changed it to white or added something to differentiate the themes https://github.com/glandium/tabstats/issues/9

This one differentiates too https://addons.mozilla.org/en-US/firefox/addon/tabber/

This one too https://addons.mozilla.org/en-US/firefox/addon/second-search/

**Comment by hensm** [comment]
Yeah, they use `theme_icons`. The problem is that it would only work for the reload icon. No way to specify a flipped icon for RTL locales either.

I’ll just add an override option.

**Comment by rayman89** [comment]
It's white now for me thank you.
